matrix:
  include:
    - os: linux
      go: 1.10.x
      language: go

before_script:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

script:
  go test -v -covermode=count -coverprofile=coverage.out ./...
- bingoveralls -service=travis-ci -coverprofile=coverage.out -repotoken $COVERALLS_TOKEN
